--기존에 존재하는 route 테이블 삭제
DROP TABLE IF EXISTS route;
--테이블 column 추가
CREATE TABLE route (
                       id INT PRIMARY KEY,
                       destination VARCHAR(255),
                       startingpoint VARCHAR(255),
                       route VARCHAR(255),
                       emoji0 VARCHAR(255),
                       text1 VARCHAR(255),
                       emoji1 VARCHAR(255),
                       text2 VARCHAR(255),
                       emoji2 VARCHAR(255),
                       text3 VARCHAR(255),
                       emoji3 VARCHAR(255),
                       text4 VARCHAR(255),
                       emoji4 VARCHAR(255),
                       text5 VARCHAR(255),
                       emoji5 VARCHAR(255),
                       text6 VARCHAR(255),
                       emoji6 VARCHAR(255),
                       text7 VARCHAR(255),
                       emoji7 VARCHAR(255)
);
--엑셀로 가공한 데이터 insert
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (1, '경영관', '포스코관', 'walk', 'marker', '포스코관 B1F', 'stair, elev', '포스코관 출구 - 학문관 2F', 'walking', '학문관 B1F', 'stair, elev', '수영장길', 'walking', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (2, '공학관', '후문', 'walk', 'marker', '학문관 B1F', 'walking', '학문관 2F 출구', 'stair, elev', '포스코관 B1F', 'walking', '포스코관 4F', 'stair, elev', '포스코관 쪽문 - 종합과학관 D동 B1F', 'walking', '종합과학관 D동 4F', 'stair, elev', '종합과학관 쪽문- 공대삼거리(좌회전)', 'walking');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (3, '공학관', '후문', 'bus', 'marker', '학문관 B1F', 'walking', '학문관 2F 출구', 'stair, elev', '포스코관 정류장 - 공대삼거리 정류장', 'bus', '공대삼거리(좌회전)', 'walking', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (4, '공학관', '학관', 'walk', 'marker', '학관 6F', 'stair, elev', '학관 구름다리 - 포스코관 B1F', 'walking', '포스코관 4F', 'stair, elev', '포스코관 쪽문 - 종합과학관 D동 B1F', 'walking', '종합과학관 D동 4F', 'stair, elev', '종합과학관 쪽문 - 공대삼거리(좌회전)', 'walking', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (5, '공학관', '학관', 'bus', 'marker', '학관 6F', 'stair, elev', '학관 구름다리 - 포스코관 B1F', 'walking', '포스코관 정류장 - 공대삼거리 정류장', 'bus', '공대삼거리(좌회전)', 'walking', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (6, '공학관', '포스코관', 'walk', 'marker', '포스코관 4F', 'stair, elev', '포스코관 쪽문 - 종합과학관 D동 B1F', 'walking', '종합과학관 D동 4F', 'stair, elev', '종합과학관 쪽문 - 공대삼거리(좌회전)', 'walking', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (7, '공학관', '포스코관', 'bus', 'marker', '포스코관 정류장 - 공대삼거리 정류장', 'bus', '공대삼거리(좌회전)', 'walking', '', '', '', '', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (8, '공학관', '연구협력관', 'walk', 'marker', '연구협력관 1F', 'stair, elev', '징공다리', 'stair', '', '', '', '', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (9, '기숙사', '정문', 'walk', 'marker', '걷기(입학관 옆)', 'walking', '걷기(헬렌관 옆)', 'walking', '법학관 4F', 'stair, elev', '걷기(좌회전)', 'walking', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (10, '기숙사', '정문', 'bus', 'marker', '정문 정류장 - 기숙사 정류장', 'bus', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (11, '기숙사', '연구협력관', 'walk', 'marker', '걷기 (셔틀 도로 따라서)', 'walking', '이하우스 쪽문 계단', 'stair', '', '', '', '', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (12, '기숙사', '연구협력관', 'bus', 'marker', '연구협력관 정류장 - 기숙사 정류장', 'bus', '걷기(직진)', 'walking', '', '', '', '', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (13, '법학관', '학관', 'walk', 'marker', '학관 6F', 'stair, elev', '학관 구름다리 - 포스코관 B1F', 'walking', '포스코관 1F 출구', 'stair, elev', '포스코관 1F 출구(좌회전)', 'walking', '포도길(직진)', 'walking', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (14, '법학관', '포스코관', 'walk', 'marker', '포스코관 1F 출구', 'stair, elev', '포스코관 1F 출구 나온 후 좌회전', 'walking', '포도길(직진)', 'walking', '', '', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (15, '생활관', '포스코관', 'walk', 'marker', '포스코관 B1F 출구', 'stair, elev', '학생문화관 쪽문', 'walking', '학생문화관 1F 출구', 'stair, elev', '걷기(우회전)', 'walking', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (16, '생활관', '종합과학관', 'walk', 'marker', '종합과학관 D동 B1F', 'stair, elev', '종합과학관 D동 B1F - 포스코관 쪽문', 'walking', '포스코관 B1F', 'stair, elev', '포스코관 B1F - 학생문화관 쪽문', 'walking', '학생문화관 1F출구', 'stair, elev', '생활관 1F(우회전)', 'walking', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (17, '생활관', '종합과학관', 'bus', 'marker', '종합과학관 D동 4F', 'stair, elev', '공대삼거리 정류장 - 포스코관 정류장', 'bus', '포스코관 B1F - 학생문화관 쪽문', 'walking', '학생문화관 B1F', 'stair, elev', '생활관 1F(우회전)', 'walking', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (18, '연구협력관', '공학관', 'walk', 'marker', '징공다리', 'stair', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (19, '연구협력관', '기숙사', 'walk', 'marker', '이하우스 쪽문 계단', 'stair', '걷기 (셔틀 도로 따라서)', 'walking', '', '', '', '', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (20, '연구협력관', '기숙사', 'bus', 'marker', '걷기(직진)', 'walking', '기숙사 정류장 - 연구협력관 정류장', 'bus', '', '', '', '', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (21, '정문', '기숙사', 'walk', 'marker', '걷기(직진)', 'walking', '법학관 B1F', 'stair, elev', '걷기(헬렌관 옆)', 'walking', '걷기(입학관 옆)', 'walking', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (22, '정문', '기숙사', 'bus', 'marker', '기숙사 정류장 - 정문 정류장', 'bus', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (23, '정문', '종합과학관', 'walk', 'marker', '종합과학관 D동 B1F', 'stair, elev', '종합과학관 D동 B1F - 포스코관 쪽문', 'walking', '포스코관 B1F', 'stair, elev', '걷기(ecc, 대강당 사잇길)', 'walking', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (24, '정문', '종합과학관', 'bus', 'marker', '종합과학관 D동 4F', 'stair, elev', '공대삼거리 정류장 - 정문 정류장', 'bus', '', '', '', '', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (25, '종합과학관', '후문', 'walk', 'marker', '학문관 B1F', 'walking', '학문관 2F 출구', 'stair, elev', '포스코관 4F', 'stair, elev', '포스코관 쪽문 - 종합과학관 D동 B1F', 'walking', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (26, '종합과학관', '후문', 'bus', 'marker', '학문관 B1F', 'walking', '학문관 2F 출구', 'stair, elev', '포스코관 정류장 - 공대삼거리 정류장', 'bus', '', '', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (27, '종합과학관', '학관', 'walk', 'marker', '학관 6F', 'stair, elev', '학관 구름다리 - 포스코관 B1F', 'walking', '포스코관 4F', 'stair, elev', '포스코관 쪽문 - 종합과학관 D동 B1F', 'walking', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (28, '종합과학관', '포스코관', 'walk', 'marker', '포스코관 4F', 'stair, elev', '포스코관 쪽문 - 종합과학관 D동 B1F', 'walking', '', '', '', '', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (29, '종합과학관', '정문', 'walk', 'marker', '걷기(ecc, 대강당 사잇길)', 'walking', '포스코관 B1F', 'walking', '포스코관 4F', 'stair, elev', '포스코관 쪽문 - 종합과학관 D동 B1F', 'walking', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (30, '종합과학관', '정문', 'bus', 'marker', '정문 정류장 - 공대삼거리 정류장', 'bus', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (31, '종합과학관', '생활관', 'walk', 'marker', '생활관 1F (우회전)', 'walking', '학생문화관 1F 입구', 'walking', '학문관 2F 출구', 'stair, elev', '포스코관 4F', 'stair, elev', '포스코관 쪽문 - 종합과학관 D동 B1F', 'walking', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (32, '종합과학관', '생활관', 'bus', 'marker', '생활관 1F (우회전)', 'walking', '학생문화관 1F 입구', 'walking', '학문관 2F 출구', 'stair, elev', '포스코관 정류장 - 공대삼거리 정류장', 'bus', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (33, '포스코관', '경영관', 'walk', 'marker', '수영장길', 'walking', '학문관 B1F', 'walking', '학문관 2F 출구', 'stair, elev', '포스코관 B1F 입구', 'walking', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (34, '포스코관', '공학관', 'walk', 'marker', '신공학관 3F', 'stair, elev', '신공학관 3F- 공대 삼거리(직진)', 'walking', '공대삼거리- 포스코관 B1F(우회전 후 직진)', 'walking', '', '', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (35, '포스코관', '공학관', 'bus', 'marker', '신공학관 3F', 'stair, elev', '신공학관 3F - 공대 삼거리(직진)', 'walking', '공대삼거리 정류장 - 포스코관 정류장', 'bus', '', '', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (36, '포스코관', '법학관', 'walk', 'marker', '포도길(역사관 끼고 직진)', 'walking', '포스코관 1F 입구', 'walking', '', '', '', '', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (37, '포스코관', '생활관', 'walk', 'marker', '걷기(우회전)', 'walking', '학생문화관 B1F 입구', 'walking', '학생문화관 2F', 'stair, elev', '학생문화관 쪽문 - 포스코관 B1F', 'walking', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (38, '포스코관', '종합과학관', 'walk', 'marker', '종합과학관 D동 B1F', 'stair, elev', '종합과학관 D동 B1F - 포스코관 쪽문', 'walking', '', '', '', '', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (39, '학관', '공학관', 'walk', 'marker', '신공학관 3F', 'stair, elev', '신공학관 3F - 공대 삼거리(직진)', 'walking', '공대삼거리- 포스코관 B1F(우회전 후 직진)', 'walking', '학관 6F 구름다리', 'walking', '', '', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (40, '학관', '공학관', 'bus', 'marker', '신공학관 3F', 'stair, elev', '신공학관 3F - 공대 삼거리 (직진)', 'walking', '공대삼거리 정류장 - 포스코관 정류장', 'bus', '포스코관 B1F - 학관 구름다리', 'walking', '학관 6F', 'stair, elev', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (41, '학관', '법학관', 'walk', 'marker', '포도길 (역사관 끼고 직진)', 'walking', '포스코관 1F 입구', 'walking', '포스코관 B1F', 'stair, elev', '포스코관 B1F - 학관 구름다리', 'walking', '학관 6F', 'stair, elev', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (42, '학관', '종합과학관', 'walk', 'marker', '종합과학관 D동 B1F', 'stair, elev', '종합과학관 D동 B1F - 포스코관 쪽문', 'walking', '포스코관 B1F', 'stair, elev', '포스코관 B1F - 학관 구름다리', 'walking', '학관 6F', 'stair, elev', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (43, '후문', '공학관', 'walk', 'marker', '신공학관 3F', 'stair, elev', '신공학관 3F- 공대 삼거리(직진)', 'walking', '공대삼거리- 포스코관 B1F(우회전 후 직진)', 'walking', '학문관 2F 입구', 'walking', '학문관 B1F 출구', 'stair, elev', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (44, '후문', '공학관', 'bus', 'marker', '신공학관 3F', 'stair, elev', '신공학관 3F- 공대 삼거리(직진)', 'walking', '공대삼거리 정류장 - 포스코관 정류장', 'bus', '학문관 2F 입구', 'walking', '학문관 B1F 출구', 'stair, elev', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (45, '후문', '종합과학관', 'walk', 'marker', '종합과학관 D동 B1F', 'stair, elev', '종합과학관 D동 B1F - 포스코관 쪽문', 'walking', '포스코관 B1F', 'stair, elev', '포스코관 B1F - 학관 구름다리', 'walking', '학생문화관 B1F', 'stair, elev', '', '', '', '');
INSERT INTO route (id, destination, startingpoint, route, emoji0, text1, emoji1, text2, emoji2, text3, emoji3, text4, emoji4, text5, emoji5, text6, emoji6, text7, emoji7) VALUES (46, '후문', '종합과학관', 'bus', 'marker', '종합과학관 D동 4F', 'stair, elev', '공대삼거리 정류장 - 포스코관 정류장', 'bus', '포스코관 B1F - 학생문화관 쪽문', 'walking', '학생문화관 B1F', 'stair, elev', '', '', '', '', '', '');

/*
    destination: 도착지
    startingpoint: 출발지
*/